server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/threetanks?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl